/**
 * Inhalte der Spülmaschinen-FAQ auf /Afwasmachine.
 *
 * Reine Daten – die Darstellung übernimmt components/DeviceFaqSection.tsx.
 * Aus derselben Liste wird auch das FAQPage-Schema der Seite erzeugt.
 */

import { business } from "./business";
import type { FaqItem } from "./kaffeeFaq";

/** Marken, für die Geschirrspüler repariert werden. */
export const dishwasherBrands = [
  "Miele",
  "Siemens",
  "Bosch",
  "Privileg",
  "Bauknecht",
  "Whirlpool",
  "Bomann",
  "Fagor",
  "Blomberg",
  "Liebherr",
  "Constructa",
  "Neff",
  "Indesit",
  "Goronje",
  "Hanseatic",
  "Beko",
  "Amica",
  "Ariston",
  "EBD",
  "Candy",
  "Lloyds",
  "Philips",
  "Hoover",
  "Zanussi",
  "Foron",
  "Juno",
  "LG",
  "SEG",
  "AEG",
  "Küppersbusch",
  "Samsung",
  "Panasonic",
  "Grundig",
];

/** Ersatzteile, die für Geschirrspüler vorgehalten und verbaut werden. */
export const dishwasherSpareParts = [
  "Elektronik",
  "Laugenpumpe",
  "Umwälzpumpe",
  "Heizelement",
  "Temperaturfühler",
  "Pumpenwellendichtung",
  "Pumpenflügel",
  "Laufradsatz",
  "Pumpenkopf",
  "Pumpenlager",
  "Lecksensoren",
  "Entstörschutz",
  "Störschutzfilter",
  "Kondensator",
  "Magnetventil",
  "Druckwächter",
  "Wasserstandsregler",
  "Mikroschalter",
  "Dosierkombination",
  "Dosierkombination-Auslöser",
  "Kleinschutz",
  "Heizelementrelais",
  "Temperaturbegrenzer",
  "Dichtungen",
  "Programmschaltwerk",
  "Elektronikgehäuse",
  "Tastenschalter",
  "Endschalter",
  "Drehwechselschalter",
  "Knebel für Programmschalter",
  "Knebelring",
  "Enthärtungsanlage",
  "Deckel für Salzbehälter",
  "Lüftergitter",
  "Lüfter",
  "Druckschlagventil",
  "Regenerierungsdosierung",
  "Verbindungsschlauch",
  "Türdichtung",
  "Wrasenschutz",
  "Reparatursatz-Kabelbaum",
  "Türschloss",
  "Umlenkscheibe unten",
  "Türscharnier",
  "Seilzug",
  "Türgriff",
  "Scharnierabdeckung",
  "Türfeder",
  "Zugband",
  "Türfederhaken",
  "Zugbandschloss",
  "Federanschluss",
  "Bremsbock",
  "Sprüharm",
  "Düse für Sprüharm",
  "Sprüharmzulaufhalter",
  "Sprühkopf",
  "Sprüharmrohr",
  "Sprüharmführung",
  "Gegenmutter Sprüharmzuflussrohr",
  "Rändelmutter",
  "Gegenmutter",
  "Lagerbuchse",
  "Sprüharmbefestigungsmutter",
  "Sprüharmbefestigungsumbausatz",
  "Sprüharmflansch",
  "Verschlusskappe",
  "Grobsieb Kunststoff/Metall",
  "Feinsieb",
  "Mikrosieb",
  "Siebeinsatz Grobsieb",
  "Griff für Feinsieb",
  "Filter für Betriebszeitzähler-Behälter",
  "Mikrofeinfilter",
  "Geschirrkorb",
  "Korbrollen",
  "Korbschienenanschlagsatz",
  "Clip für Korbrolle",
  "Korbrollenachse",
  "Lampe",
  "Gerätefuß",
  "Schwimmer",
  "Durchflussmengenmesser",
  "Ablaufschlauch",
  "Zulaufschlauch",
];

export const dishwasherFaqs: FaqItem[] = [
  {
    id: "pumpen",
    question: "Welche Aufgaben haben die Pumpen im Geschirrspüler und welche zwei Arten gibt es?",
    answer:
      "An jedem Geschirrspüler befinden sich zwei Pumpen. Die Laugenpumpe hat die Aufgabe, das Wasser des Geschirrspülers nach dem Spülen in den Rohrabfluss zu pumpen. Die Umwälzpumpe dient dazu, das sich im Gerät befindliche Wasser in der Wassertasche (Regenerierdosierung) mit hohem Druck durch die beiden Sprüharme (oben und unten) auf das Geschirr zu sprühen, um es zu reinigen.",
  },
  {
    id: "essensreste",
    question: "Wie können Essensreste zu Schäden führen und wie erkennt man diesen Fehler frühzeitig?",
    answer:
      "Essensreste können dazu führen, dass die Pumpen verklemmen und durch den Dauerbetrieb zu heiß werden, wodurch die Wicklung des Trafos durchschmort und das Gerät ausfällt. Den Fehler erkennt man anfänglich an dem nach und nach lauter werdenden Abpumpgeräusch. Dann sollte das Gerät schnellstmöglich ausgeschaltet und vom Netz genommen werden, um die Pumpe zu reinigen.",
  },
  {
    id: "wasserventile",
    question: "Welche Folgen haben verkalkte Wasserventile?",
    answer:
      "Verkalkte Wasserventile bewirken, dass das Gerät kein oder zu wenig Wasser einlässt, was den Spülbetrieb verhindert. Zu wenig Wasser kann dazu führen, dass das Heizelement unterbricht oder durchbrennt (Heizungsausfall) und der Temperaturfühler Schaden nimmt. Durch die hohe Hitze können auch Dichtungssätze beschädigt werden, was zu Wasserverlust führen kann.",
  },
  {
    id: "anfahrt",
    question: "Wie viel kosten Anfahrt und Kostenvoranschlag und wie lautet die Notrufnummer?",
    answer: `Für Berlin und Umland kosten Anfahrt + Kostenvoranschlag nur ${business.calloutFee} €. Die Notrufnummer lautet: ${business.telephoneDisplay}.`,
  },
  {
    id: "garantie",
    question: "Wie lange ist die Reparaturgarantie der Firma KURT?",
    answer: "Die Firma KURT gewährt drei Jahre Garantie auf die Reparatur.",
  },
  {
    id: "leihgeraet",
    question: "Was passiert, wenn die Reparatur länger als drei Werktage dauert?",
    answer:
      "Falls die Reparatur länger als drei Werktage in Anspruch nimmt, stellt die Firma KURT kostenlos ein Leihgerät zur Verfügung.",
  },
  {
    id: "marken",
    question: "Welche Marken für Geschirrspüler-Reparaturen werden auf der Seite genannt?",
    answer: dishwasherBrands.join(", ") + ".",
  },
  {
    id: "ersatzteile",
    question: "Welche Ersatzteile für Geschirrspüler werden auf der Seite aufgelistet?",
    answer: dishwasherSpareParts.join(", ") + ".",
  },
];
